import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/icomoon.css";
import { Providers } from "./providers";
import { Footer } from "@/components/Footer/Footer";
import { Header } from "@/components/header/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/svg/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="min-h-screen">
        <Providers>
          <Header />
          <main className="page-container">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
